name: chess_mas
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  collection: ^1.18.0
  args: ^2.4.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
